In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6065, 6765, 4631, 6533], [6065, 6765, 4631, 5835], [6065, 998, 4631, 5833], [2373, 9267, 515, 1306, 3642], [2373, 9267, 515, 1306, 5662], [5254, 6065, 2308, 4631, 1778], [6276, 8057, 8961, 1306]]


Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6065 6765 4631 6533]
 [   0    0    0    0 6065 6765 4631 5835]
 [   0    0    0    0 6065  998 4631 5833]
 [   0    0    0 2373 9267  515 1306 3642]
 [   0    0    0 2373 9267  515 1306 5662]
 [   0    0    0 5254 6065 2308 4631 1778]
 [   0    0    0    0 6276 8057 8961 1306]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692
    0.04240714 -0.00552188 -0.00610914 -0.00632545 -0.02470561]
  [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692
    0.04240714 -0.00552188 -0.00610914 -0.00632545 -0.02470561]
  [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692
    0.04240714 -0.00552188 -0.00610914 -0.00632545 -0.02470561]
  [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692
    0.04240714 -0.00552188 -0.00610914 -0.00632545 -0.02470561]
  [ 0.04392887  0.01061153 -0.00411823  0.04041579  0.01587081
   -0.04857139 -0.01970564 -0.01934772 -0.03943179 -0.01122317]
  [ 0.03738966 -0.01379672 -0.03365172  0.02969045 -0.02636316
    0.02259359 -0.00297916 -0.04756199 -0.02788704 -0.00571231]
  [-0.0063652   0.01901711 -0.03068176 -0.02938186 -0.02885038
   -0.02436548 -0.04553828 -0.00851481 -0.00162166 -0.0466748 ]
  [-0.01213454  0.0051079   0.00155244 -0.0230472   0.04702691
   -0.01167883  0.01599062 -0.03379323 -0.036045

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6065, 6765, 4631, 6533], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692  0.04240714
  -0.00552188 -0.00610914 -0.00632545 -0.02470561]
 [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692  0.04240714
  -0.00552188 -0.00610914 -0.00632545 -0.02470561]
 [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692  0.04240714
  -0.00552188 -0.00610914 -0.00632545 -0.02470561]
 [-0.02650557  0.03764342  0.00527303  0.01836712 -0.02907692  0.04240714
  -0.00552188 -0.00610914 -0.00632545 -0.02470561]
 [ 0.04392887  0.01061153 -0.00411823  0.04041579  0.01587081 -0.04857139
  -0.01970564 -0.01934772 -0.03943179 -0.01122317]
 [ 0.03738966 -0.01379672 -0.03365172  0.02969045 -0.02636316  0.02259359
  -0.00297916 -0.04756199 -0.02788704 -0.00571231]
 [-0.0063652   0.01901711 -0.03068176 -0.02938186 -0.02885038 -0.02436548
  -0.04553828 -0.00851481 -0.00162166 -0.0466748 ]
 [-0.01213454  0.0051079   0.00155244 -0.0230472   0.04702691 -0.01167883
   0.01599062 -0.03379323 -0.03604595  0.02222632]]

Summary:


1.   Sentences
2.   OneHot Representation => get index from vocab size Range.
3.   Embedded layer keras to form embedding matrix.
2.   Eembedding matrix vocab_size = 10 000 and dimension=10





